### ISSUE TITLE
Allow two or more paragraphs in category heading

### ISSUE THREAD

**Issue by hmoldenhauer** [pep-dortmund/towards-a-new-website#10]
Right now, the second paragraph in the category description is rendered in a smaller and italic type.

Can we get rid of this behaviour? I suspect it has something to do with the `header p:first-of-type` in the `css`

**Comment by bixel** [comment]
Will we ever have more then one paragraph there? We said that if so, one should use a custom template and move the second paragraph and all other content into a `<div class="box">` element.

**Comment by MaxNoe** [comment]
Currently under discussion is the `bachelorkolloquium`, where we want to add a paragraph just containing `Alle sind herzlich eingeladen!`.

> Will we ever have more then one paragraph there? We said that if so, one should use a custom template.

If we say, we usually do not want to have more than one paragraph there, i would find it more intuitive if there is no special rule for the first paragraph.
