### ISSUE TITLE
different layouts in "Über uns" and "Vereinsleben"

### ISSUE THREAD

**Issue by hmoldenhauer** [pep-dortmund/towards-a-new-website#11]
In "Vereinsleben" the descriptions are content, while in "Über uns" descriptions are given in subtitles.

**Comment by bixel** [comment]
Its the layout `page` vs. `category`. Since we didn't want to display posts within "Über uns" these are static sites. But I agree that this might be a bit confusing.

by the way: its awkward to write the issues and everything in english and having a german website and even german filenames...

**Comment by MaxNoe** [comment]
Yes, i would rather keep everything but content in english, but this is just my own taste.

**Comment by bixel** [comment]
We could open a new issue for that :trollface:

**Comment by MaxNoe** [comment]
Yeah.
