### ISSUE TITLE
Size of drop down menu

### ISSUE THREAD

**Issue by hmoldenhauer** [pep-dortmund/towards-a-new-website#12]
Changing name from "Protokolle der MV" to "Mitgliederversammlung" doesn't resize the drop down menue. It should be dynamically resized in case of adding or changing some points.

**Comment by bixel** [comment]
The menu is not generated by the filenames or md headers of files. It is generated from `_data/navigation.yml` since jekyll is not that flexible here. RTFM! Oh... its not done yet. See #8

**Comment by bixel** [comment]
Ah sorry, the problem still exists. I misunderstood the issue.
